### ISSUE TITLE
WAFER-IMX8MP - VNC failed

### ISSUE THREAD

**Issue by sinyfu** [QNAP-android-internal/meta-iei-imx-bsp#1]
Our factory users have reported that there is no VNC remote desktop solution available, whether using Yocto or Ubuntu. Is there a way to support this?

**Comment by wigcheng** [comment]
You can adapt RDP remote desktop way on our Yocto 5.0, here is the steps as following:

**Server side (WAFER-IMX8MP)**
Step 1. generate the key an crt files
`mkdir -p ~/.pki/CA/private/`
`cd ~/.pki/CA`
`openssl genrsa -out private/cakey.pem 2048`
`openssl req -new -x509 -nodes -days 365000 -key private/cakey.pem -out cacert.pem`
`openssl genrsa -out tls.key 2048`
`openssl req -new -key tls.key -out tls.csr`
`openssl req -new -key tls.key -out tls.csr -subj "/CN=wafer-imx8mp"`
`openssl x509 -req -days 365 -in tls.csr -out tls.crt -CA cacert.pem -CAkey`
`private/cakey.pem`

Step 2. move these two files to specific folder and rename to server.crt and server.key
`mv tls.key /etc/freerdp/keys/server.key`
`mv tls.crt /etc/freerdp/keys/server.crt`

Step 3. modify /etc/xdg/weston/weston.ini as follows:
`[core]`
`#gbm-format=argb8888`
`use-g2d=false`
`repaint-window=16`
`idle-time=0`
`xwayland=true`
`#enable-overlay-view=1`

`[screen-share]`
`command=/usr/bin/weston --backend=rdp-backend.so --shell=fullscreen-shell.so --no-clients-resize`
`command=/usr/bin/weston --backend=rdp-backend.so --rdp-tls-cert=/etc/freerdp/keys/server.crt --rdp-tls key=/etc/freerdp/keys/server.key --shell=fullscreen-shell.so --no-clients-resize`
`start-on-startup=true`

Step 4. modify the /etc/systemd/system/graphical.target.wants/weston.service
`[Service]`
`# Requires systemd-notify.so Weston plugin.`
`Type=notify`
`EnvironmentFile=/etc/default/weston`
`ExecStartPre=-/usr/bin/setup-weston-init.sh`
`ExecStart=/usr/bin/weston --log=${XDG_RUNTIME_DIR}/weston.log --modules=systemd-notify.so,screen-share.so`

**Client side (host PC with Ubuntu 24.04)**
Step 1. Install relate packages 
`sudo apt install freerdp2-x11 # (for X11)`
`sudo apt install freerdp2-wayland # (for wayland)`

Step 2. Connect to the target board
`xfreerdp /v:<IP address> # (for X11)`
`wlfreerdp /v:<IP address> # (for wayland)`

Test Results
![image](https://github.com/user-attachments/assets/1c49cdc2-f760-407a-9595-710a5c1b7293)

Relate patches will update you soon.

About VNC, it still has some problem on Yocto 5.0, we will take a look what is going on.
In addition, Ubuntu adapts Gnome Desktop with xwayland, so it's another story, we will find a solution for that.

Thanks

**Comment by wigcheng** [comment]
@sinyfu 

All commits for RDP solution has been uploaded to github, just repo sync again and enjoy!
In addition, we will study how to implement remote desktop on Gnome Wayland soon.

**Comment by sinyfu** [comment]
works fine, thanks! I will close the ticket and looking forward your Gnome solution.
